name: Imaging Cloud Analyzer Action
env:
  version: 1
on:
  # push:
  #   branches: [ swi ]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  run-imaging-cloud-analyzer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Imaging Cloud Action
        run: |
          cd ${{github.workspace}}
          ls -alsht $(pwd)
          docker run -v $(pwd)/src:/home/carl/extras/source -v $(pwd)/swi:/home/carl/extras/results -e IMAGING_CLOUD_API_KEY=${{secrets.IMAGING_CLOUD_API_KEY}} -e REPO_URL=${{github.server_url}}/${{github.repository}} -e IMAGING_CLOUD_ACTION_FILE_VERSION=${{env.version}} castimaging/imaging-cloud-action:latest
