name: Imaging Cloud Analyzer Action
env:
  version: 1
  results: all_results
on:
  # push:
  #   branches: [ swi ]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  run-imaging-cloud-analyzer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Imaging Cloud Action
        run: |
          cd ${{github.workspace}}
          mkdir ./${{env.results}} 
          chmod a+w ./${{env.results}} 
          touch ./${{env.results}}/README.md
          docker run -v ${{github.workspace}}/${{env.results}}:/home/carl/extras/results -v ${{github.workspace}}/source:/home/carl/extras/source -e IMAGING_CLOUD_API_KEY=${{secrets.IMAGING_CLOUD_API_KEY}} -e REPO_URL=${{github.server_url}}/${{github.repository}} -e IMAGING_CLOUD_ACTION_FILE_VERSION=${{env.version}} castimaging/imaging-cloud-action:latest
          ls -alsht ${{github.workspace}}/${{env.results}}/fastscan
          ls -alsht ${{github.workspace}}/${{env.results}}/deep-analysis
      - uses: actions/upload-artifact@v4
        with:
          name: repo-swi
          path: ${{github.workspace}}/${{env.results}}
